services:
#    rsv_deploy.example:
#        class: Rsv\DeployBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    project.service:
        class: Rsv\DeployBundle\Manager\ProjectManager
        arguments: [ "@doctrine.orm.entity_manager" ]

    comand.service:
        class: Rsv\DeployBundle\Manager\CommandDataManager
        arguments: [ "@doctrine.orm.entity_manager" ]
